version: "3"

services:

  node1:
    image: "ufoscout/galera-mariadb:latest"
    build: .
    hostname: node1
    ports:
      - 3306:3306
     # - 4444:4444
     # - 4567:4567
     # - 4568:4568
    environment:
      WSREP_NEW_CLUSTER: 1
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      WSREP_NODE_NAME: node1
      WSREP_CLUSTER_NAME: galera_cluster
      WSREP_CLUSTER_ADDRESS: gcomm://node1

  node2:
    image: "ufoscout/galera-mariadb:latest"
    hostname: node2
    links:
    - node1
    ports:
    - 3307:3306
    environment:
      WAIT_HOSTS: node1:3306
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      WSREP_NODE_NAME: node2
      WSREP_CLUSTER_NAME: galera_cluster
      WSREP_CLUSTER_ADDRESS: gcomm://node1
      
  node3:
    image: "ufoscout/galera-mariadb:latest"
    hostname: node3
    links:
    - node1
    ports:
    - 3308:3306
    environment:
      WAIT_HOSTS: node1:3306
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      WSREP_NODE_NAME: node3
      WSREP_CLUSTER_NAME: galera_cluster
      WSREP_CLUSTER_ADDRESS: gcomm://node1
