version: "3"

services:

  node1:
    image: "codership/galera-mariadb:10.3"
    build: .
    hostname: node1
    ports:
      - 3306:3306
    environment:
      WSREP_NEW_CLUSTER: 1
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      WSREP_NODE_NAME: node1
      WSREP_CLUSTER_NAME: galera_cluster
      WSREP_CLUSTER_ADDRESS: gcomm://node1

  node2:
    image: "codership/galera-mariadb:10.3"
    hostname: node2
    links:
    - node1
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      WSREP_NODE_NAME: node2
      WSREP_CLUSTER_NAME: galera_cluster
      WSREP_CLUSTER_ADDRESS: gcomm://node1
      
  node3:
    image: "codership/galera-mariadb:10.3"
    hostname: node3
    links:
    - node1
    ports:
    - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      WSREP_NODE_NAME: node3
      WSREP_CLUSTER_NAME: galera_cluster
      WSREP_CLUSTER_ADDRESS: gcomm://node1
