version: "3"

services:

  node1:
    image: "codership/galera-mysql:5.6"
    build: .
    hostname: node1
    ports:
      - "3306:3306"
    command: mysqld --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://
   
  node2:
    image: "codership/galera-mysql:5.6"
    hostname: node2
    ports:
      - "3307:3306"
    command: mysqld --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://node1

  node3:
    image: "codership/galera-mysql:5.6"
    hostname: node3
    ports:
      - "3307:3306"
    command: mysqld --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://node1    
